"""
推送通知模块
将简报发送到 Slack 和 Telegram。
"""
import json
import re
import urllib.request
import config


def _build_slack_blocks(briefing: str, articles: list = None) -> list:
    """
    构建 Slack Block Kit blocks。
    从 briefing 文本提取概览，从 articles 结构化数据构建每条带可点击链接的卡片。
    """
    blocks = []

    # --- 从 briefing 提取标题和概览 ---
    lines = briefing.strip().split("\n")
    title = ""
    overview = ""
    for line in lines:
        stripped = line.strip()
        if not title and stripped:
            title = stripped
        elif "[今日概览]" in stripped or "[今日概览]" in stripped:
            overview = stripped
            break
        elif not overview and stripped and not re.match(r'^\[?\d+\]', stripped):
            overview = stripped

    if title:
        blocks.append({
            "type": "header",
            "text": {"type": "plain_text", "text": title[:150]}
        })
    if overview:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": overview}
        })
    blocks.append({"type": "divider"})

    # --- 从 briefing 文本中提取每条的说明文字 ---
    item_texts = {}  # index -> text
    current_idx = None
    current_lines = []

    for line in lines:
        match = re.match(r'^\[?(\d+)\]?\s', line.strip())
        if match:
            if current_idx is not None:
                item_texts[current_idx] = "\n".join(current_lines)
            current_idx = int(match.group(1))
            current_lines = [line.strip()]
        elif current_idx is not None:
            stripped = line.strip()
            if stripped and stripped != "---" and not stripped.startswith("Generated by"):
                # 跳过链接行（由结构化数据提供）
                if not re.match(r'^(链接[：:]|https?://)', stripped):
                    current_lines.append(stripped)

    if current_idx is not None:
        item_texts[current_idx] = "\n".join(current_lines)

    # --- 用结构化数据构建每条卡片 ---
    if articles:
        for i, art in enumerate(articles, 1):
            # 从 briefing 提取该条的说明文字
            text = item_texts.get(i, "")
            if not text:
                text = f"*[{i}]* {art.title}\n_{art.source}_\n{art.summary[:200]}"

            # 加粗编号
            text = re.sub(r'^\[?(\d+)\]?\s*', r'*[\1]* ', text, count=1)

            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": text[:2900]},
                "accessory": {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Read more"},
                    "url": art.url,
                }
            })
            blocks.append({"type": "divider"})
    else:
        # Fallback: 没有结构化数据时从文本解析
        for idx, text in sorted(item_texts.items()):
            text = re.sub(r'^\[?(\d+)\]?\s*', r'*[\1]* ', text, count=1)
            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": text[:3000]}
            })
            blocks.append({"type": "divider"})

    blocks.append({
        "type": "context",
        "elements": [{"type": "mrkdwn", "text": "Generated by AI Daily Briefing"}]
    })

    return blocks


def send_to_slack(briefing: str, articles: list = None) -> bool:
    """通过 Slack Incoming Webhook 发送简报（Block Kit 富文本 + 可点击按钮）"""
    if not config.SLACK_ENABLED:
        print("[Notifier] Slack 未配置，跳过")
        return False

    blocks = _build_slack_blocks(briefing, articles)

    # Slack 限制每条消息最多 50 个 blocks
    batch_size = 48
    success = True

    for i in range(0, len(blocks), batch_size):
        batch = blocks[i:i + batch_size]
        payload = json.dumps({
            "text": briefing[:200],
            "blocks": batch,
            "unfurl_links": False,
        }).encode("utf-8")

        try:
            req = urllib.request.Request(
                config.SLACK_WEBHOOK_URL,
                data=payload,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                result = resp.read().decode("utf-8")
            if result != "ok":
                print(f"[Notifier] Slack batch {i//batch_size + 1} 异常: {result}")
                success = False
        except Exception as e:
            print(f"[Notifier] Slack Block Kit 发送失败: {e}, 尝试纯文本...")
            try:
                fallback = json.dumps({"text": briefing, "unfurl_links": False}).encode("utf-8")
                req2 = urllib.request.Request(
                    config.SLACK_WEBHOOK_URL, data=fallback,
                    headers={"Content-Type": "application/json"}, method="POST",
                )
                with urllib.request.urlopen(req2, timeout=15) as resp2:
                    resp2.read()
                print("[Notifier] Slack 纯文本 fallback 成功")
            except Exception as e2:
                print(f"[Notifier] Slack fallback 也失败: {e2}")
            success = False

    if success:
        print(f"[Notifier] Slack 发送成功 ({len(blocks)} blocks)")
    return success


def send_to_telegram(briefing: str) -> bool:
    """通过 Telegram Bot API 发送简报"""
    if not config.TELEGRAM_ENABLED:
        print("[Notifier] Telegram 未配置，跳过")
        return False

    # Telegram 消息有 4096 字符限制，超长时分段发送
    max_len = 4000
    chunks = []
    remaining = briefing
    while remaining:
        if len(remaining) <= max_len:
            chunks.append(remaining)
            break
        # 在换行符处截断
        cut = remaining[:max_len].rfind("\n")
        if cut < max_len // 2:
            cut = max_len
        chunks.append(remaining[:cut])
        remaining = remaining[cut:].lstrip("\n")

    api_base = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}"
    success = True

    for i, chunk in enumerate(chunks):
        payload = json.dumps({
            "chat_id": config.TELEGRAM_CHAT_ID,
            "text": chunk,
            "parse_mode": "Markdown",
            "disable_web_page_preview": True,
        }).encode("utf-8")

        try:
            req = urllib.request.Request(
                f"{api_base}/sendMessage",
                data=payload,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read().decode("utf-8"))
            if not data.get("ok"):
                print(f"[Notifier] Telegram 片段 {i+1} 发送异常: {data}")
                success = False
        except Exception as e:
            print(f"[Notifier] Telegram 片段 {i+1} 发送失败: {e}")
            success = False

    if success:
        print(f"[Notifier] Telegram 发送成功 ({len(chunks)} 条消息)")
    return success


def send_html_to_slack_ja(html: str) -> bool:
    """日本語版HTMLブリーフィングを別のSlackチャンネルに送信"""
    if not config.SLACK_JA_ENABLED:
        print("[Notifier] Slack日本語版 未配置，跳过")
        return False

    if not html:
        print("[Notifier] HTML内容为空，跳过日本語版")
        return False

    # HTMLをSnippetとして送信（Slackがファイルとしてプレビュー）
    # Incoming Webhookではファイル添付不可なので、HTMLリンク付きメッセージを送信
    # 代替方案：HTML内容のテキスト要約を送信
    import re
    from datetime import datetime as dt

    today = dt.now().strftime("%Y-%m-%d")

    # HTMLからテキスト版を抽出してSlackに送信
    blocks = []

    # Header
    blocks.append({
        "type": "header",
        "text": {"type": "plain_text", "text": f"AI Daily Briefing - {today} (日本語版)"}
    })

    # overview抽出
    overview_match = re.search(r'overview-label[^>]*>.*?</div>\s*(.*?)\s*</div>', html, re.DOTALL)
    if overview_match:
        overview_text = re.sub(r'<[^>]+>', '', overview_match.group(1)).strip()
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": overview_text[:3000]}
        })

    blocks.append({"type": "divider"})

    # 各カードを抽出
    card_pattern = re.compile(
        r'card-num[^>]*>(\d+)</span>.*?'
        r'card-title[^>]*>(.*?)</h2>.*?'
        r'class="tag[^"]*">(.*?)</span>.*?'
        r'class="region[^"]*">(.*?)</span>.*?'
        r'card-source[^>]*>(.*?)</span>.*?'
        r'card-body[^>]*>(.*?)</div>.*?'
        r"(?:href='([^']*)'[^>]*>.*?Read more)?",
        re.DOTALL
    )

    for match in card_pattern.finditer(html):
        num, title, tag, region, source, body, url = match.groups()
        title = re.sub(r'<[^>]+>', '', title or '').strip()
        body = re.sub(r'<[^>]+>', '', body or '').strip()
        tag = re.sub(r'<[^>]+>', '', tag or '').strip()
        region = re.sub(r'<[^>]+>', '', region or '').strip()
        source = re.sub(r'<[^>]+>', '', source or '').strip()

        text = f"*[{num}]* {title} | [{tag}] | [{region}]\n_{source}_\n{body}"

        block = {
            "type": "section",
            "text": {"type": "mrkdwn", "text": text[:2900]},
        }
        if url:
            block["accessory"] = {
                "type": "button",
                "text": {"type": "plain_text", "text": "Read more"},
                "url": url,
            }
        blocks.append(block)
        blocks.append({"type": "divider"})

    blocks.append({
        "type": "context",
        "elements": [{"type": "mrkdwn", "text": "Generated by AI Daily Briefing (日本語版)"}]
    })

    # 送信
    batch_size = 48
    success = True

    for i in range(0, len(blocks), batch_size):
        batch = blocks[i:i + batch_size]
        payload = json.dumps({
            "text": "AI Daily Briefing 日本語版",
            "blocks": batch,
            "unfurl_links": False,
        }).encode("utf-8")

        try:
            req = urllib.request.Request(
                config.SLACK_WEBHOOK_URL_JA,
                data=payload,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                result = resp.read().decode("utf-8")
            if result != "ok":
                print(f"[Notifier] Slack日本語版 batch {i//batch_size+1} 異常: {result}")
                success = False
        except Exception as e:
            print(f"[Notifier] Slack日本語版 送信失敗: {e}")
            success = False

    if success:
        print(f"[Notifier] Slack日本語版 送信成功 ({len(blocks)} blocks)")
    return success


def notify(briefing: str, articles: list = None, html_ja: str = "") -> dict:
    """发送简报到所有已配置的渠道"""
    results = {}

    # 中文版 → Slack Block Kit
    if config.SLACK_ENABLED:
        results["slack_cn"] = send_to_slack(briefing, articles)

    # 日本語版 → HTML ファイル保存（GitHub Pages で公開）
    if html_ja:
        try:
            from datetime import datetime as dt
            filename = f"briefing_{dt.now().strftime('%Y%m%d')}_ja.html"
            with open(filename, "w", encoding="utf-8") as f:
                f.write(html_ja)
            print(f"[Notifier] 日本語HTML保存: {filename}")
            results["html_ja"] = True
        except Exception as e:
            print(f"[Notifier] 日本語HTML保存失敗: {e}")
            results["html_ja"] = False

    if config.TELEGRAM_ENABLED:
        results["telegram"] = send_to_telegram(briefing)

    if not results:
        print("[Notifier] ⚠️ 没有配置任何推送渠道！请设置 SLACK_WEBHOOK_URL 或 TELEGRAM_BOT_TOKEN")

    return results
